Feature/lmsdemo 115
EscolaLMS/Components pull request #113
Opened 2022-05-27 12:38 UTC by victazzz

2022-05-27 13:32 UTC, pieecia commented on src/components/players/Audio/Audio.md
> +import { GlobalThemeProvider } from "../../../theme/provider";
redundant import

2022-05-30 10:57 UTC, qunabu requested changes

2022-05-30 10:57 UTC, qunabu commented on src/components/players/Audio/Audio.md
> +      url="https://api-stage.escolalms.com//storage/course/7/topic/736/audio/siwCEwd14f7mPtY1rmfxcYovSTF73wKN1Sx3F7SL.mp4"
replace URL with something that won't change in future

2022-05-30 10:57 UTC, qunabu commented on src/components/players/Audio/Audio.tsx
> +interface TrackProps {
https://microsoft.github.io/PowerBI-JavaScript/interfaces/_node_modules_typedoc_node_modules_typescript_lib_lib_dom_d_.audiotrack.html

2022-05-30 10:57 UTC, qunabu commented on src/components/players/Audio/Audio.tsx
> +        <audio
don't use browser audio use VideoPlayer component of something similar 

it should look like videoplayer with same capaliticies

2022-05-30 11:21 UTC, qunabu commented
use VideoPlayer from components it is based on https://github.com/cookpete/react-player and does player video with tracks 

you can rename this components to AudioVideoPlayer

2022-05-31 07:22 UTC, qunabu approved these changes

2022-05-31 07:23 UTC, merged