LMSDEMO-18 - ProfileAvatar
EscolaLMS/Components pull request #18
Opened 2022-04-28 12:30 UTC by pieecia

przygotowałem ten komponent jako avatar, bez asocjacji tekstu itd poniewaz wydaje mi sie, ze moze byc wykorzystywany w wielu miejscach, przygotowalem tez wariant "large" ktory podejrzalem w zakladce "opis wykonawcy" 

od siebie bym renamowalbym komponent na czysty "avatar", nazwa jest bardziej uniwersalna

2022-04-28 14:10 UTC, qunabu requested changes
make those components simpler

2022-04-28 14:10 UTC, qunabu commented on src/components/primitives/ProfileAvatar/ProfileAvatar.tsx
> +  }};
KISS principle 

```suggestion
  width: ${(props) => prop.size === "large" ? "116px" : "50px",
  height: ${(props) => prop.size === "large" ? "116px" : "50px",
```

2022-04-29 07:17 UTC, pieecia commented on src/components/primitives/ProfileAvatar/ProfileAvatar.tsx
> +  height: ${props => setProfileAvatarBySize(props.size)};
okazalo sie ze rozmiarow jest wiecej, wiec przygotowalem funkcje zeby nie powtarzac kodu

2022-04-29 12:22 UTC, qunabu requested changes

2022-04-29 12:22 UTC, qunabu commented on src/components/primitives/ProfileAvatar/ProfileAvatar.tsx
> +  style?: React.CSSProperties;
style is already in React.ImgHTMLAttributes<HTMLImageElement> 

https://microsoft.github.io/PowerBI-JavaScript/interfaces/_node_modules_typedoc_node_modules_typescript_lib_lib_dom_d_.htmlimageelement.html#style

2022-04-29 12:22 UTC, qunabu commented on src/components/primitives/ProfileAvatar/ProfileAvatar.md
>  <GlobalThemeProvider>
replace `<GlobalThemeProvider>` with `ThemeTester` example https://github.com/EscolaLMS/Components/blob/main/src/components/primitives/Badge/Badge.md

2022-04-29 12:32 UTC, qunabu approved these changes

2022-04-29 12:33 UTC, merged