LMSDEMO-156 - Lightbox style
EscolaLMS/Components pull request #189
Opened 2022-06-22 06:49 UTC by pieecia

2022-06-22 07:40 UTC, qunabu commented
you can't import css into components, it won't work (due to webpack etc) 

you must copy css code into styled components 

see how this was done in modal https://github.com/EscolaLMS/Components/blob/main/src/components/atoms/Modal/Modal.tsx

2022-06-22 07:40 UTC, qunabu requested changes
you can't import css into components, it won't work (due to webpack etc)

you must copy css code into styled components

see how this was done in modal https://github.com/EscolaLMS/Components/blob/main/src/components/atoms/Modal/Modal.tsx

2022-06-22 07:45 UTC, qunabu requested changes
you should just import this `StyledImagePlayer` and wrap player around lightbox 

https://github.com/EscolaLMS/Components/blob/main/src/components/players/ImagePlayer/ImagePlayer.tsx

because DRY and this style is already in the code

2022-06-23 06:26 UTC, pieecia commented
> you should just import this `StyledImagePlayer` and wrap player around lightbox
> 
> https://github.com/EscolaLMS/Components/blob/main/src/components/players/ImagePlayer/ImagePlayer.tsx
> 
> because DRY and this style is already in the code

I couldn't reuse `StyledImagePlayer` because i had a problem with interfaces, so I took style to utils and imported to components

2022-06-23 10:25 UTC, qunabu requested changes

2022-06-23 10:25 UTC, qunabu commented on src/components/molecules/MarkdownRenderer/MarkdownRenderer.tsx
> +import "react-image-lightbox/style.css";
```suggestion
```

2022-06-23 12:54 UTC, qunabu approved these changes

2022-06-23 12:54 UTC, merged