LMSDEMO - 19 - add ProgressBar component with styles
EscolaLMS/Components pull request #21
Opened 2022-04-29 12:39 UTC by postrowinski

2022-04-29 12:48 UTC, qunabu requested changes

2022-05-02 06:48 UTC, postrowinski commented on src/components/primitives/ProgressBar/ProgressBar.tsx
> +          <span className="filled" style={{ width: percentageValue() }}></span>
The starting point for the XY scaling is, the points placed halfway up the height and width of the html element, so to change this we'll create some chaos in CSS. So according to the KISS principle, I only change the type of animation in width.

2022-05-04 06:36 UTC, pieecia commented on src/components/primitives/ProgressBar/ProgressBar.tsx
> +          <span className="filled" style={{ width: percentageValue() }}></span>
> When adding scaling, we cannot control the border-radius parameter. Additionally, the starting point for XY scaling are the points placed in the middle of the height and width of the html element, so to change this we will create chaos in CSS. So according to the KISS principle, I only change the type of animation in width.

have you tried to add a new inner span to an existing `<span className="filled">`? 

check out the live working demo https://mui.com/material-ui/react-progress/#customization

2022-05-04 10:59 UTC, qunabu commented on src/components/primitives/ProgressBar/ProgressBar.tsx
> +          <span className="filled" style={{ width: percentageValue() }}></span>
We can fix this in next iteration of this component

2022-05-04 10:59 UTC, merged