Feature/lmsdemo 10 input
EscolaLMS/Components pull request #24
Opened 2022-05-04 12:57 UTC by postrowinski

2022-05-04 16:05 UTC, qunabu requested changes

2022-05-04 16:05 UTC, qunabu commented on src/components/primitives/Input/Input.tsx
> +  error?: string;
why error must be a string ?

2022-05-05 05:39 UTC, postrowinski commented on src/components/primitives/Input/Input.tsx
> +  required?: boolean;
1. error not exist in HTMLInputElement
2. container is main wrapping html element added for the future is you need added some className or style.
3. required yes is duplicated, so i remove that.

2022-05-05 08:41 UTC, qunabu commented on src/components/primitives/Input/Input.tsx
> +  required?: boolean;
sorry I've selected to much lines by accident, this comment was just for `required` line

2022-05-05 08:55 UTC, qunabu approved these changes

2022-05-05 08:55 UTC, merged